# _config.yml
remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0
gh_sponsor: brownrw8
footer_menu: footer
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page
      title: "Ê»ÅŒlelo Honua ðŸŒº"
      hero_image: /images/hero_new.png
